# Generated by Django 3.2 on 2021-12-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MdlServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('fqdn', models.CharField(max_length=100, verbose_name='fqdn')),
                ('role_name', models.CharField(max_length=100, null=True, verbose_name='角色名称')),
                ('ip', models.CharField(max_length=100)),
                ('user', models.CharField(default='root', max_length=30, verbose_name='用户')),
                ('remote_python', models.CharField(max_length=100, verbose_name='远端python')),
                ('consul_space', models.CharField(max_length=300, verbose_name='consul 地址')),
                ('consul_token', models.CharField(max_length=100, verbose_name='token')),
                ('install_dir', models.CharField(max_length=100, verbose_name='安装目录')),
                ('backups_dir', models.CharField(max_length=100, verbose_name='备份目录')),
                ('service_name', models.CharField(max_length=100, verbose_name='服务名')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
