# Generated by Django 3.2 on 2021-12-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdlserver',
            name='fqdn',
            field=models.CharField(max_length=100, unique=True, verbose_name='fqdn'),
        ),
    ]
