# Generated by Django 3.2 on 2021-12-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdl', '0002_alter_mdlserver_fqdn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mdlserver',
            old_name='backups_dir',
            new_name='backup_dir',
        ),
        migrations.AlterField(
            model_name='mdlserver',
            name='fqdn',
            field=models.CharField(max_length=100, verbose_name='fqdn'),
        ),
        migrations.AlterUniqueTogether(
            name='mdlserver',
            unique_together={('fqdn', 'service_name')},
        ),
    ]
