# Generated by Django 3.2 on 2021-12-29 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdl', '0003_auto_20211229_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mdlserver',
            old_name='backup_dir',
            new_name='backups_dir',
        ),
    ]
