# Generated by Django 3.2 on 2022-01-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdl', '0004_rename_backup_dir_mdlserver_backups_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdlserver',
            name='check_detail',
            field=models.CharField(max_length=200, null=True, verbose_name='检查结果详细信息'),
        ),
        migrations.AddField(
            model_name='mdlserver',
            name='is_consistent',
            field=models.BooleanField(default=True, verbose_name='是否与生产信息一致'),
        ),
    ]
