# Generated by Django 3.2 on 2022-04-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdl', '0005_auto_20220118_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdlserver',
            name='config_git_url',
            field=models.CharField(max_length=200, null=True, verbose_name='配置文件git链接(只生产环境的机器需要配置)'),
        ),
    ]
