# Generated by Django 3.2 on 2022-09-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdl', '0006_mdlserver_config_git_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdlserver',
            name='check_detail',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='检查结果详细信息'),
        ),
        migrations.AlterField(
            model_name='mdlserver',
            name='config_git_url',
            field=models.CharField(blank=True, help_text='生产环境需填git配置文件路径,stg环境不需要', max_length=200, null=True, verbose_name='配置文件git链接'),
        ),
    ]
