# Generated by Django 3.2 on 2022-12-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdl', '0007_auto_20220905_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='标签名')),
                ('mdl_server', models.ManyToManyField(blank=True, to='mdl.MdlServer', verbose_name='mdl_server')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
