# Generated by Django 3.2 on 2023-01-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdl', '0008_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdlserver',
            name='consul_files',
            field=models.CharField(default='feeder_handler.cfg', max_length=50, verbose_name='consul中的配置文件'),
        ),
    ]
