# Generated by Django 3.2 on 2023-09-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdl', '0009_mdlserver_consul_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdlserver',
            name='consul_files',
            field=models.CharField(default='feeder_handler.cfg', help_text='如果不是feeder_handler.cfg配置文件，请改成实际的配置文件名称', max_length=50, verbose_name='consul中的配置文件'),
        ),
    ]
