# Generated by Django 3.2.25 on 2026-02-25 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdl', '0010_alter_mdlserver_consul_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='服务类型名称')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '服务类型',
                'verbose_name_plural': '服务类型',
            },
        ),
        migrations.CreateModel(
            name='ConfigInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='实例名称')),
                ('host_ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='主机IP')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='端口')),
                ('config_path', models.CharField(blank=True, max_length=300, null=True, verbose_name='配置目录路径')),
                ('service_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='服务名')),
                ('install_dir', models.CharField(blank=True, max_length=200, null=True, verbose_name='安装目录')),
                ('backups_dir', models.CharField(blank=True, max_length=200, null=True, verbose_name='备份目录')),
                ('consul_space', models.CharField(blank=True, max_length=300, null=True, verbose_name='Consul KV 前缀')),
                ('consul_files', models.CharField(default='feeder_handler.cfg', max_length=200, verbose_name='Consul 配置文件列表')),
                ('remote_python', models.CharField(default='/usr/bin/python3', max_length=100, verbose_name='远端 Python 路径')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdl.servicetype', verbose_name='服务类型')),
            ],
            options={
                'verbose_name': '配置实例',
                'verbose_name_plural': '配置实例',
                'unique_together': {('service_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ConfigDeployTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('operator', models.CharField(max_length=100, verbose_name='操作人')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=20, verbose_name='任务状态')),
                ('log', models.TextField(blank=True, null=True, verbose_name='执行日志')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('instances', models.ManyToManyField(blank=True, to='mdl.ConfigInstance', verbose_name='部署实例')),
            ],
            options={
                'verbose_name': '配置部署任务',
                'verbose_name_plural': '配置部署任务',
            },
        ),
        migrations.CreateModel(
            name='ConfigFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('filename', models.CharField(max_length=200, verbose_name='文件名')),
                ('content', models.JSONField(blank=True, null=True, verbose_name='配置内容(JSON)')),
                ('raw_content', models.TextField(blank=True, null=True, verbose_name='原始内容')),
                ('git_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Git 路径')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdl.configinstance', verbose_name='所属实例')),
            ],
            options={
                'verbose_name': '配置文件',
                'verbose_name_plural': '配置文件',
                'unique_together': {('instance', 'filename')},
            },
        ),
    ]
