# Generated by Django 3.2.25 on 2026-03-06 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdl', '0018_mdloperationlog_systemdservicecache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configauditlog',
            name='action',
            field=models.CharField(choices=[('save', '保存配置'), ('batch_update', '批量修改'), ('text_replace', '文本替换'), ('git_commit', '提交 Git'), ('push_consul', '推送 Consul'), ('deploy', 'Ansible 部署'), ('sync', '同步 GitLab'), ('server_init', '服务器初始化'), ('server_create', '新增服务器'), ('server_delete', '删除服务器')], max_length=30, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='configauditlog',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='configauditlog',
            name='deploy_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='mdl.configdeploytask'),
        ),
        migrations.AlterField(
            model_name='configauditlog',
            name='last_updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='mdlserver',
            name='consul_files',
            field=models.CharField(default='feeder_handler.cfg', help_text='Consul 中的配置文件名，多个用逗号分隔，如 feeder_handler.cfg,feeder_receiver.cfg', max_length=200, verbose_name='consul中的配置文件'),
        ),
        migrations.AlterField(
            model_name='mdlserver',
            name='role_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='角色名称'),
        ),
        migrations.CreateModel(
            name='ConfigHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.JSONField(verbose_name='配置内容快照')),
                ('action', models.CharField(choices=[('save', '保存配置'), ('batch_update', '批量修改'), ('text_replace', '文本替换'), ('rollback', '回滚'), ('deploy_snapshot', '部署前快照')], default='save', max_length=20, verbose_name='触发操作')),
                ('operator', models.CharField(default='system', max_length=100, verbose_name='操作人')),
                ('remark', models.CharField(blank=True, default='', max_length=300, verbose_name='备注')),
                ('config_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='mdl.configfile', verbose_name='配置文件')),
            ],
            options={
                'verbose_name': '配置历史',
                'verbose_name_plural': '配置历史',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddField(
            model_name='configdeploytask',
            name='snapshots',
            field=models.ManyToManyField(blank=True, related_name='deploy_tasks', to='mdl.ConfigHistory', verbose_name='部署前快照'),
        ),
    ]
