# Generated by Django 3.2.25 on 2026-03-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdl', '0019_auto_20260306_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdlserver',
            name='executable',
            field=models.CharField(default='feeder_handler', help_text='systemd ExecStart 中的可执行文件名，如 feeder_handler、feeder_dispatcher', max_length=100, verbose_name='可执行文件名'),
        ),
    ]
