# Generated by Django 3.2 on 2021-06-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('key', models.CharField(default='', max_length=50)),
                ('value', models.TextField()),
                ('type', models.CharField(choices=[('str', 'str'), ('json', 'json'), ('list', 'list'), ('int', 'int')], default='str', max_length=10)),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述信息')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
