# Generated by Django 3.2 on 2021-09-30 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('owner', models.CharField(max_length=100, verbose_name='创建人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReleaseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('index', models.IntegerField(verbose_name='发布顺序')),
                ('issue_key', models.CharField(max_length=50, verbose_name='jira工单')),
                ('release_version', models.CharField(max_length=100, verbose_name='发布版本')),
                ('rancher_app_version', models.CharField(max_length=200, verbose_name='rancher app 版本')),
                ('release_plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.releaseplan', verbose_name='所属发布计划')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
