# Generated by Django 3.2 on 2021-10-11 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseplan',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='名称'),
        ),
        migrations.CreateModel(
            name='ReleaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.CharField(max_length=50, verbose_name='执行发布用户')),
                ('status', models.CharField(default='升级中', max_length=20, verbose_name='状态信息')),
                ('prompt', models.CharField(default='开始升级', max_length=100, verbose_name='提示信息')),
                ('step', models.IntegerField(default=1, verbose_name='流程步骤')),
                ('log', models.TextField(null=True)),
                ('release_plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.releaseplan', verbose_name='所属发布计划')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
