# Generated by Django 3.2 on 2021-10-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211011_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasedetail',
            name='step',
        ),
        migrations.AddField(
            model_name='releasedetail',
            name='active',
            field=models.IntegerField(default=0, verbose_name='前端流程图当前位置'),
        ),
    ]
