# Generated by Django 3.2 on 2021-10-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211011_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasedetail',
            name='active',
        ),
        migrations.AddField(
            model_name='releasedetail',
            name='step_status',
            field=models.JSONField(default=1, verbose_name='流程图中各个模块的执行状态信息'),
        ),
        migrations.AlterField(
            model_name='releasedetail',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='releasedetail',
            name='status',
            field=models.CharField(default='升级中', max_length=20, verbose_name='任务状态信息'),
        ),
    ]
