# Generated by Django 3.2 on 2021-10-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211012_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasedetail',
            name='step_status',
            field=models.JSONField(null=True, verbose_name='流程图中各个模块的执行状态信息'),
        ),
    ]
