# Generated by Django 3.2 on 2021-10-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_releasedetail_step_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasecontent',
            name='is_release',
            field=models.BooleanField(default=True, verbose_name='是否发布'),
        ),
        migrations.AddField(
            model_name='releasedetail',
            name='active',
            field=models.IntegerField(default=1, verbose_name='流程图当前发布的位置'),
        ),
    ]
