# Generated by Django 3.2 on 2021-10-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211012_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasecontent',
            name='current_version',
            field=models.CharField(max_length=200, null=True, verbose_name='发布前的版本'),
        ),
    ]
