# Generated by Django 3.2 on 2021-10-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_releasecontent_current_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasecontent',
            name='current_version',
        ),
        migrations.AddField(
            model_name='releasecontent',
            name='current_rancher_app_version',
            field=models.CharField(max_length=200, null=True, verbose_name='发布前的rancher app 版本'),
        ),
    ]
