# Generated by Django 3.2 on 2021-10-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211013_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasecontent',
            name='status',
            field=models.CharField(choices=[('process', 'process'), ('wait', 'wait'), ('error', 'error'), ('success', 'success')], default='wait', max_length=20, null=True, verbose_name='发布状态'),
        ),
    ]
