# Generated by Django 3.2 on 2021-10-13 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_releasecontent_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasedetail',
            name='step_status',
        ),
        migrations.AlterField(
            model_name='releasecontent',
            name='release_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.releaseplan', verbose_name='所属发布计划'),
        ),
        migrations.AlterField(
            model_name='releasedetail',
            name='status',
            field=models.CharField(choices=[('升级中', '升级中'), ('失败', '失败'), ('成功', '成功'), ('暂停', '暂停')], default='升级中', max_length=20, verbose_name='任务状态'),
        ),
    ]
