# Generated by Django 3.2 on 2021-10-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211013_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasedetail',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='releasedetail',
            name='status',
            field=models.CharField(choices=[('发布中', '发布中'), ('发布失败', '发布失败'), ('发布成功', '发布成功'), ('暂停', '暂停'), ('回滚中', '回滚中'), ('回滚成功', '回滚成功'), ('回滚失败', '回滚失败')], default='升级中', max_length=20, verbose_name='任务状态'),
        ),
    ]
