# Generated by Django 3.2 on 2021-10-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211014_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseplan',
            name='project',
            field=models.CharField(default='OPS', max_length=100, verbose_name='项目'),
        ),
    ]
