# Generated by Django 3.2 on 2021-10-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_releaseplan_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseplan',
            name='plan_release_time',
            field=models.DateTimeField(null=True, verbose_name='计划发布时间'),
        ),
        migrations.AlterField(
            model_name='releaseplan',
            name='project',
            field=models.CharField(max_length=100, verbose_name='项目'),
        ),
    ]
