# Generated by Django 3.2 on 2021-11-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211030_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasecontent',
            name='config_file',
            field=models.JSONField(null=True, verbose_name='配置文件'),
        ),
    ]
