# Generated by Django 3.2 on 2021-12-23 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_releasecontent_config_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MdlReleaseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('index', models.IntegerField(verbose_name='发布顺序')),
                ('issue_key', models.CharField(max_length=50, verbose_name='jira工单')),
                ('release_version', models.CharField(max_length=100, verbose_name='发布版本')),
                ('is_release', models.BooleanField(default=True, verbose_name='是否发布')),
                ('status', models.CharField(choices=[('process', 'process'), ('wait', 'wait'), ('error', 'error'), ('success', 'success')], default='wait', max_length=20, null=True, verbose_name='发布状态')),
                ('config_file', models.JSONField(null=True, verbose_name='配置文件')),
                ('server', models.CharField(max_length=100, verbose_name='服务器')),
                ('type', models.CharField(choices=[('仅配置变更', '仅配置变更'), ('版本发布', '版本发布')], max_length=20, null=True, verbose_name='发布类型')),
                ('release_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.releaseplan', verbose_name='所属发布计划')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
