# Generated by Django 3.2 on 2021-12-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_mdlreleasecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdlreleasecontent',
            name='type',
            field=models.CharField(choices=[('config', '仅配置变更'), ('version', '版本发布')], max_length=20, null=True, verbose_name='发布类型'),
        ),
    ]
