# Generated by Django 3.2 on 2021-12-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_mdlreleasecontent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdlreleasecontent',
            name='current_version',
            field=models.CharField(max_length=100, null=True, verbose_name='当前版本'),
        ),
    ]
