# Generated by Django 3.2 on 2021-12-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_mdlreleasecontent_current_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdlreleasecontent',
            name='release_version',
            field=models.CharField(max_length=100, null=True, verbose_name='发布版本'),
        ),
    ]
