# Generated by Django 3.2 on 2021-12-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_mdlreleasecontent_release_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdlreleasecontent',
            name='server',
        ),
        migrations.AddField(
            model_name='mdlreleasecontent',
            name='release_object',
            field=models.CharField(max_length=100, null=True, verbose_name='发布对象 服务器+服务名'),
        ),
    ]
