# Generated by Django 3.2 on 2021-12-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20211229_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdlreleasecontent',
            name='release_object',
            field=models.CharField(max_length=200, verbose_name='发布对象 服务器+服务名'),
        ),
    ]
