# Generated by Django 3.2 on 2022-03-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_mdlreleasecontent_release_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseplan',
            name='category',
            field=models.CharField(default='正常发布', max_length=20, verbose_name='发布类型'),
        ),
        migrations.AlterField(
            model_name='mdlreleasecontent',
            name='config_file',
            field=models.JSONField(blank=True, null=True, verbose_name='配置文件'),
        ),
        migrations.AlterField(
            model_name='mdlreleasecontent',
            name='current_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='当前版本'),
        ),
        migrations.AlterField(
            model_name='mdlreleasecontent',
            name='issue_key',
            field=models.CharField(blank=True, max_length=50, verbose_name='jira工单'),
        ),
        migrations.AlterField(
            model_name='mdlreleasecontent',
            name='release_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='发布版本'),
        ),
    ]
