# Generated by Django 3.2 on 2022-03-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20220304_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseplan',
            name='category',
            field=models.CharField(default='正常发布', max_length=20, null=True, verbose_name='发布类型'),
        ),
    ]
