# Generated by Django 3.2 on 2022-09-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_releaseplan_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasecontent',
            name='depconf_ticket_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='配置发布系统中的ticket名称'),
        ),
    ]
