# Generated by Django 3.2 on 2023-09-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_releasecontent_depconf_ticket_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseplan',
            name='is_auto',
            field=models.BooleanField(default=False, verbose_name='自动发布'),
        ),
    ]
