# for version odler than 2.13.36
# package_name: mdl_release-{{ version }}.tar.gz
package_name: market_data_line-{{ version }}.tar.gz
package_url: http://artifactory.datayes.com/artifactory/mdl-release/com/datayes/market_data_line/{{ version }}/{{ package_name }}
executable: feeder_handler
install_items:
  - "{{ executable }}"
  - libmdl_api.so
backup_items:
  - "{{ executable }}"
  - "{{ consul_files.split(',')[0] | trim }}"
  - libmdl_api.so
  - version
put_files: []
