- name: set backup dir
  set_fact: backup_dir={{ backups_dir }}/{{ executable | default('feeder_handler') }}_{{ existing_version }}_{{ ansible_date_time.iso8601_basic_short }}

- name: backup install dir
  command: cp -r {{ install_dir }} {{ backup_dir }}
  become: true
