- debug: msg="deploying feeder_handler config"

- name: check python
  include_tasks: check_python.yml

- name: check version
  include_tasks: check_version.yml
  tags:
    - version
- debug: msg="已安装版本:{{ existing_version }}"

- name: stop
  when: existing_version != "null"
  include_tasks: stop.yml

- name: backup
  when: existing_version != "null"
  include_tasks: backup.yml

- name: config
  include_tasks: config.yml

- name: start
  when: start_after_deploy | default(True)
  include_tasks: start.yml
