# Generated by Django 3.2 on 2021-07-08 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=30, verbose_name='名字')),
                ('status', models.CharField(max_length=30, verbose_name='当前状态')),
                ('dev_owner', models.CharField(max_length=30, verbose_name='开发负责人')),
                ('ops_owner', models.CharField(max_length=30, verbose_name='运维负责人')),
                ('arch_owner', models.CharField(max_length=30, verbose_name='架构负责人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('description', models.TextField(null=True, verbose_name='描述')),
                ('dev_owner', models.CharField(max_length=100, null=True, verbose_name='开发负责人')),
                ('ops_owner', models.CharField(max_length=100, null=True, verbose_name='运维负责人')),
                ('arch_owner', models.CharField(max_length=100, null=True, verbose_name='架构负责人')),
                ('deploy_loc', models.CharField(max_length=30, null=True, verbose_name='部署位置')),
                ('if_containerize', models.BooleanField(default=True, verbose_name='是否容器化')),
                ('deploy_env', models.CharField(max_length=30, null=True, verbose_name='部署环境')),
                ('is_oem', models.BooleanField(default=False, verbose_name='是否落地项目')),
                ('consul_space', models.CharField(max_length=100, null=True, verbose_name='Consul 空间名称')),
                ('registry_project', models.CharField(max_length=100, null=True, verbose_name='镜像仓库所属的项目')),
                ('release_artifact_name', models.CharField(max_length=100, null=True, verbose_name='镜像发布仓库名')),
                ('git_url', models.CharField(max_length=200, verbose_name='代码仓库')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='代号')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('manager', models.CharField(blank=True, max_length=100, null=True, verbose_name='负责人')),
                ('type', models.CharField(blank=True, choices=[('公共服务', '公共服务'), ('数据平台', '数据平台'), ('Office IT', 'Office IT'), ('其他', '其他')], max_length=100, verbose_name='类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='项目名')),
                ('cluster_id', models.CharField(max_length=100, null=True, verbose_name='rancher中项目所属集群id')),
                ('project_id', models.CharField(max_length=100, null=True, verbose_name='rancher中项目id')),
                ('env', models.CharField(max_length=30, null=True, verbose_name='rancher 环境')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='工作负载名')),
                ('namespace_id', models.CharField(max_length=300, null=True, verbose_name='命名空间')),
                ('state', models.CharField(max_length=20, null=True, verbose_name='状态')),
                ('type', models.CharField(max_length=50, null=True, verbose_name='类型')),
                ('workload_id', models.CharField(max_length=300, null=True, verbose_name='rancher中workload id')),
                ('url', models.CharField(max_length=200, null=True, verbose_name='访问url')),
                ('consul_server', models.CharField(max_length=100, null=True, verbose_name='consul 服务器')),
                ('consul_token', models.CharField(max_length=300, null=True, verbose_name='consul token')),
                ('consul_url', models.CharField(max_length=300, null=True, verbose_name='consul地址')),
                ('app_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.appmodule')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('namespace', models.CharField(max_length=100, verbose_name='命名空间')),
                ('pod_ip', models.GenericIPAddressField(null=True)),
                ('node_name', models.CharField(max_length=100, verbose_name='pod所属的节点名')),
                ('host_ip', models.GenericIPAddressField(null=True, verbose_name='node ip地址')),
                ('env', models.CharField(choices=[('stag', 'stag'), ('qa', 'qa'), ('prod', 'prod')], max_length=20, null=True, verbose_name='环境')),
                ('app_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.appmodule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200, null=True, verbose_name='ingress名')),
                ('namespace_id', models.CharField(max_length=300, null=True, verbose_name='命名空间')),
                ('state', models.CharField(max_length=20, null=True, verbose_name='状态')),
                ('host', models.CharField(max_length=200, null=True, verbose_name='访问url')),
                ('app_module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.appmodule')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.project')),
                ('workload_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.workload')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
