# Generated by Django 3.2 on 2021-07-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='App',
        ),
    ]
