# Generated by Django 3.2 on 2021-08-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pod',
            name='env',
            field=models.CharField(max_length=20, null=True, verbose_name='环境'),
        ),
    ]
