# Generated by Django 3.2 on 2021-08-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pod_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodule',
            name='init_arch_owner',
            field=models.CharField(max_length=100, null=True, verbose_name='初始架构负责人'),
        ),
        migrations.AddField(
            model_name='appmodule',
            name='init_dev_owner',
            field=models.CharField(max_length=100, null=True, verbose_name='初始开发负责人'),
        ),
        migrations.AddField(
            model_name='appmodule',
            name='init_ops_owner',
            field=models.CharField(max_length=100, null=True, verbose_name='初始运维负责人'),
        ),
    ]
