# Generated by Django 3.2 on 2021-10-12 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_attention'),
    ]

    operations = [
        migrations.CreateModel(
            name='RancherApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='名字')),
                ('app_id', models.CharField(max_length=200, verbose_name='app id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='attention',
            name='app_module',
        ),
        migrations.RemoveField(
            model_name='attention',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ingress',
            name='app_module',
        ),
        migrations.RemoveField(
            model_name='ingress',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='ingress',
            name='workload_name',
        ),
        migrations.RemoveField(
            model_name='pod',
            name='app_module',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='workload',
            name='app_module',
        ),
        migrations.RemoveField(
            model_name='workload',
            name='project_id',
        ),
        migrations.RenameModel(
            old_name='Project',
            new_name='RancherProject',
        ),
        migrations.DeleteModel(
            name='AppModule',
        ),
        migrations.DeleteModel(
            name='Attention',
        ),
        migrations.DeleteModel(
            name='Ingress',
        ),
        migrations.DeleteModel(
            name='Pod',
        ),
        migrations.DeleteModel(
            name='WorkLoad',
        ),
        migrations.AddField(
            model_name='rancherapp',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.rancherproject', verbose_name='所属项目'),
        ),
    ]
