# Generated by Django 3.2 on 2022-01-12 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211012_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='RancherWorkload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='工作负载名')),
                ('namespace_id', models.CharField(max_length=300, null=True, verbose_name='命名空间')),
                ('type', models.CharField(max_length=50, null=True, verbose_name='类型')),
                ('workload_id', models.CharField(max_length=300, null=True, verbose_name='rancher中workload id')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rancherapp')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rancherproject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
