[pytest]
DJANGO_SETTINGS_MODULE = release.settings_test
python_files = tests/test_*.py
python_classes = Test*
python_functions = test_*
# 输出详细信息
addopts = -v --tb=short
# 关闭 warnings 干扰
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
