"""
Django settings for release project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import platform

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')-ub8vv=21xluhr3ry(9li9jereq+&!q3%2-lvk4)p^+&#s@w$'

DEBUG = True

ALLOWED_HOSTS = ['*']

"""
get cur env
"""
CURRENT_HOSTNAME = platform.uname()[1].lower()

TEST_HOSTS = ["shn24015c6t7g3"]
PROD_ENV = False if CURRENT_HOSTNAME in TEST_HOSTS else True

"""
Application definition
"""

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # add external  app
    'corsheaders',
    'rest_framework',
    'django_extensions',
    'django_crontab',
    'django_filters',
    'easyaudit',
    'django_cas_ng',

    # add private app
    'api',
    'account',
    'const',
    'app',
    'mdl',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_cas_ng.middleware.CASMiddleware',
    'easyaudit.middleware.easyaudit.EasyAuditMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.middleware.exception_middleware.ExceptionMiddleware',
    'api.middleware.auth_middleware.AuthMiddleware',
    'api.middleware.disable_csrf_check.DisableCsrfCheck',
    'api.middleware.access_log_middleware.AccessLogMiddleware',
]

ROOT_URLCONF = 'release.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'release.wsgi.application'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'django_cas_ng.backends.CASBackend',
)

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

"""
rest framework
"""
REST_FRAMEWORK = {
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
        'rest_framework.permissions.AllowAny'
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'common.utils.apiutil.FitJSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer'
    ],
}

""" constance config"""

CONSTANCE_CONFIG = {
    'THE_ANSWER': (42, 'Answer to the Ultimate Question of Life, '
                       'The Universe, and Everything'),
}

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

APPEND_SLASH = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
"""
cors
"""
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

AUTH_USER_MODEL = 'account.User'

# mail
EMAIL_SUBJECT_PREFIX = '[发布系统mdl信息与生产信息不一致]'
EMAIL_HOST = 'smtp.mxhichina.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'svc-devops@datayes.com'
EMAIL_HOST_PASSWORD = 'EWArl8YtAx13'
EMAIL_SUFFIX = '@datayes.com'

DJANGO_EASY_AUDIT_UNREGISTERED_CLASSES_EXTRA = ["account.user", "app.RancherProject", "app.RancherApp"]

# wechat
ENTERPRISE_WECHAT_URL = "http://message.wmcloud.com/messages/wecom"
ENTERPRISE_WECHAT_ACCESS_TOKEN = "c59d8019792249858037f41dfc062b48"

"""
cas
"""
CAS_SERVER_URL = "http://cas.wmcloud.com/cas/login"
CAS_LOGOUT_COMPLETELY = True
CAS_VERSION = 3  # 3版本支持logout到指定的重定向页面
CAS_IGNORE_REFERER = True
CAS_REDIRECT_URL = "/admin"
CAS_AUTO_CREATE_USERS = True
CAS_GATEWAY = False
CAS_RETRY_LOGIN = True
CAS_VERIFY_SSL_CERTIFICATE = False
# CAS_CHECK_NEXT 要加上，不然会一直报Non-local url is forbidden to be redirected to.
CAS_CHECK_NEXT = lambda _: True

"""
add other settings
"""
from release.node_settings.log import *
from release.node_settings.ldap_auth import *

import os
import pydotplus

# 设置 Graphviz 可执行文件的路径
# 仅在 Windows 下设置，Linux 环境通常已在 PATH 中
if os.name == 'nt':
    os.environ["PATH"] += os.pathsep + 'C:/Program Files/Graphviz/bin/'

# =====================================================
# MDL 配置管理模块配置（config_mgmt_viewset.py 使用）
# 可在各环境的 node_settings 中覆盖以下值
# =====================================================

# GitLab 配置（用于配置文件同步和提交）
CONFIG_GITLAB_URL = os.environ.get('CONFIG_GITLAB_URL', 'http://git.datayes.com')
CONFIG_GITLAB_TOKEN = os.environ.get('CONFIG_GITLAB_TOKEN', 'aHo8e9gFFQGGqjeAE9x7')   # 与 gitlab_client.py 保持一致
CONFIG_GITLAB_PROJECT_ID = os.environ.get('CONFIG_GITLAB_PROJECT_ID', '6481')               # MDL 配置仓库 project ID
CONFIG_GITLAB_BRANCH = os.environ.get('CONFIG_GITLAB_BRANCH', 'master')
CONFIG_GITLAB_ROOT_PATH = os.environ.get('CONFIG_GITLAB_ROOT_PATH', '')                    # 如仓库根即为配置根则留空

# Consul 配置（用于推送 KV）
CONFIG_CONSUL_URL = os.environ.get('CONFIG_CONSUL_URL', 'http://consul.wmcloud.com')
CONFIG_CONSUL_TOKEN = os.environ.get('CONFIG_CONSUL_TOKEN', 'dbb8cd09-96db-36f8-fcba-a3f84e496241')  # 与 consul_client.py 保持一致
CONFIG_CONSUL_KV_PREFIX = os.environ.get('CONFIG_CONSUL_KV_PREFIX', 'configs/mdl')

# Ansible 部署目录（指向 release/ansi/mdl/）
CONFIG_ANSIBLE_DIR = os.path.join(BASE_DIR, 'ansi', 'mdl')

# Ansible SSH 认证
ANSIBLE_SSH_USER = os.environ.get('ANSIBLE_SSH_USER', 'root')
ANSIBLE_SSH_PASS = os.environ.get('ANSIBLE_SSH_PASS', '')

# 部署默认值（实例未设置时使用）
DEPLOY_DEFAULT_INSTALL_DIR = '/datayes/app/bin'
DEPLOY_DEFAULT_BACKUPS_DIR = '/datayes/app/backups'

# 下面是在不同环境会有不同的值的参数，以consul中为准
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get("DB_NAME", "release_qa"),
        'USER': os.environ.get("DB_USER", "alertcenter"),
        'PASSWORD': os.environ.get("DB_PASSWORD", "Huawei@123"),
        'HOST': os.environ.get("DB_HOST", "10.24.51.155"),
        'PORT': os.environ.get("DB_PORT", "31431"),
        'OPTIONS': {
            "init_command": "SET foreign_key_checks = 0;",
        }
    }
}

"""
每隔5分钟   */5 * * * *
每天3点钟执行  0 3 * * *
每天0点钟执行  0 0 * * *
# python manage.py crontab add 添加定时任务

"""
# CRONJOBS = [
#     ('0 0 * * *', 'app.tasks.update_app_modules_task'),
#     # ('0 2 * * *', 'app.tasks.update_rancher_projects_task'),
#     # ('15 2 * * *', 'app.tasks.update_rancher_workloads_task'),
#     # ('30 2 * * *', 'app.tasks.update_rancher_ingress_task'),
#     # ('45 2 * * *', 'app.tasks.update_pods_task'),
#     # ('0 3 * * *', 'server.tasks.server_zabbix_sync_task'),
#     # ('15 3 * * *', 'server.tasks.update_openstack_mapping_task'),
# ]
