# Generated by Django 3.2 on 2021-08-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
