# Generated by Django 3.2 on 2021-08-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_last_updated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chinese_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
