- name: set backup dir
  set_fact: backup_dir={{ backups_dir }}/{{ executable | default('feeder_handler') }}_{{ existing_version }}_{{ ansible_date_time.iso8601_basic_short }}

- name: create backup dir
  file:
    path: "{{ backup_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  become: true

- name: backup files in install_dir (exclude subdirectories)
  shell: >
    for pattern in {{ backup_items | join(' ') }} '*.cfg'; do
      for f in {{ install_dir }}/$pattern; do
        [ -f "$f" ] && cp "$f" {{ backup_dir }}/ || true;
      done;
    done
  become: true
