- name: set backup dir
  set_fact: backup_dir={{ backups_dir }}/{{ executable | default('feeder_handler') }}_{{ existing_version }}_{{ ansible_date_time.iso8601_basic_short }}

- name: create backup dir
  file:
    path: "{{ backup_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  become: true

- name: backup files in install_dir (exclude subdirectories)
  find:
    paths: "{{ install_dir }}"
    file_type: file
    max_depth: 1
  register: files_to_backup

- name: copy found files to backup directory
  copy:
    src: "{{ item.path }}"
    dest: "{{ backup_dir }}/"
    remote_src: yes
  loop: "{{ files_to_backup.files }}"
  become: true
