- name: stop service
  when: ansible_service_mgr == 'systemd'
  systemd: name={{ service_name }} state=stopped
  become: true

- name: stop service
  when: ansible_service_mgr == 'upstart'
  service: name={{ service_name }} state=stopped
  become: true

- name: wait for executable process to exit
  shell: pgrep -x {{ executable | default('feeder_handler') }}
  register: _pgrep
  until: _pgrep.rc != 0
  retries: 30
  delay: 1
  failed_when: false
  become: true


